# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GettingStarted' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SSZipArchive'

end

target 'Advanced' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SSZipArchive'

end
